/*****************************************************************************

		Copyright (c) My Company

 Project:  LogicDifusaDucha
 FileName: LOGICDIFUSADUCHA.INC
 Purpose:  Project's global declarations
 Written by: Visual Prolog
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
global domains
  DB_SELECTOR = browselist_db	% For treebrowser tool
  FILE = fileselector1; fileselector2 % To be edited

include "ingresodatos.pre"

include "reportedifusa.pre"

include "notas.pre"

include "2.pre"

include "3.pre"
